"""empty message

Revision ID: 7eb0adb432f5
Revises: 25f38a16dd13
Create Date: 2026-09-17 13:28:32.143120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb0adb432f5'
down_revision = '25f38a16dd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.String(length=20), nullable=False, server_default=sa.text("'swiss'")))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'draft'")))
        batch_op.add_column(sa.Column('max_teams', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rounds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_round', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('current_round')
        batch_op.drop_column('rounds')
        batch_op.drop_column('max_teams')
        batch_op.drop_column('status')
        batch_op.drop_column('format')

    # ### end Alembic commands ###
